/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimpleServerRouteRouteImport } from './routes/simple-server-route'
import { Route as ServerEntryPointRouteImport } from './routes/server-entry-point'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as MiddlewareRouteImport } from './routes/middleware'
import { Route as HydrationMismatchesRouteImport } from './routes/hydration-mismatches'
import { Route as GoogleRouteImport } from './routes/google'
import { Route as ErrorBoundaryRouteImport } from './routes/error-boundary'
import { Route as ClientEntryPointRouteImport } from './routes/client-entry-point'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServerRoutesIndexRouteImport } from './routes/server-routes/index'
import { Route as SelectiveSsrIndexRouteImport } from './routes/selective-ssr/index'
import { Route as ServerRoutesSomeIdRouteImport } from './routes/server-routes/$someId'
import { Route as SelectiveSsrDataOnlyRenderingRouteImport } from './routes/selective-ssr/data-only-rendering'
import { Route as SelectiveSsrClientSideRenderRouteImport } from './routes/selective-ssr/client-side-render'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as ApiDemoNamesRouteImport } from './routes/api.demo-names'
import { Route as ServerRoutesSplatSplatRouteImport } from './routes/server-routes/splat/$'
import { Route as ServerRoutesSomeDataSomeMoreDataRouteImport } from './routes/server-routes/$someData/$someMoreData'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo.start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo.start.api-request'

const SimpleServerRouteRoute = SimpleServerRouteRouteImport.update({
  id: '/simple-server-route',
  path: '/simple-server-route',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerEntryPointRoute = ServerEntryPointRouteImport.update({
  id: '/server-entry-point',
  path: '/server-entry-point',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const MiddlewareRoute = MiddlewareRouteImport.update({
  id: '/middleware',
  path: '/middleware',
  getParentRoute: () => rootRouteImport,
} as any)
const HydrationMismatchesRoute = HydrationMismatchesRouteImport.update({
  id: '/hydration-mismatches',
  path: '/hydration-mismatches',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleRoute = GoogleRouteImport.update({
  id: '/google',
  path: '/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorBoundaryRoute = ErrorBoundaryRouteImport.update({
  id: '/error-boundary',
  path: '/error-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientEntryPointRoute = ClientEntryPointRouteImport.update({
  id: '/client-entry-point',
  path: '/client-entry-point',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoutesIndexRoute = ServerRoutesIndexRouteImport.update({
  id: '/server-routes/',
  path: '/server-routes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectiveSsrIndexRoute = SelectiveSsrIndexRouteImport.update({
  id: '/selective-ssr/',
  path: '/selective-ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoutesSomeIdRoute = ServerRoutesSomeIdRouteImport.update({
  id: '/server-routes/$someId',
  path: '/server-routes/$someId',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectiveSsrDataOnlyRenderingRoute =
  SelectiveSsrDataOnlyRenderingRouteImport.update({
    id: '/selective-ssr/data-only-rendering',
    path: '/selective-ssr/data-only-rendering',
    getParentRoute: () => rootRouteImport,
  } as any)
const SelectiveSsrClientSideRenderRoute =
  SelectiveSsrClientSideRenderRouteImport.update({
    id: '/selective-ssr/client-side-render',
    path: '/selective-ssr/client-side-render',
    getParentRoute: () => rootRouteImport,
  } as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const ApiDemoNamesRoute = ApiDemoNamesRouteImport.update({
  id: '/api/demo-names',
  path: '/api/demo-names',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoutesSplatSplatRoute = ServerRoutesSplatSplatRouteImport.update({
  id: '/server-routes/splat/$',
  path: '/server-routes/splat/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerRoutesSomeDataSomeMoreDataRoute =
  ServerRoutesSomeDataSomeMoreDataRouteImport.update({
    id: '/server-routes/$someData/$someMoreData',
    path: '/server-routes/$someData/$someMoreData',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/client-entry-point': typeof ClientEntryPointRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/google': typeof GoogleRoute
  '/hydration-mismatches': typeof HydrationMismatchesRoute
  '/middleware': typeof MiddlewareRoute
  '/playground': typeof PlaygroundRoute
  '/posts': typeof PostsRouteWithChildren
  '/server-entry-point': typeof ServerEntryPointRoute
  '/simple-server-route': typeof SimpleServerRouteRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/selective-ssr/client-side-render': typeof SelectiveSsrClientSideRenderRoute
  '/selective-ssr/data-only-rendering': typeof SelectiveSsrDataOnlyRenderingRoute
  '/server-routes/$someId': typeof ServerRoutesSomeIdRoute
  '/selective-ssr': typeof SelectiveSsrIndexRoute
  '/server-routes': typeof ServerRoutesIndexRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/server-routes/$someData/$someMoreData': typeof ServerRoutesSomeDataSomeMoreDataRoute
  '/server-routes/splat/$': typeof ServerRoutesSplatSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/client-entry-point': typeof ClientEntryPointRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/google': typeof GoogleRoute
  '/hydration-mismatches': typeof HydrationMismatchesRoute
  '/middleware': typeof MiddlewareRoute
  '/playground': typeof PlaygroundRoute
  '/posts': typeof PostsRouteWithChildren
  '/server-entry-point': typeof ServerEntryPointRoute
  '/simple-server-route': typeof SimpleServerRouteRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/selective-ssr/client-side-render': typeof SelectiveSsrClientSideRenderRoute
  '/selective-ssr/data-only-rendering': typeof SelectiveSsrDataOnlyRenderingRoute
  '/server-routes/$someId': typeof ServerRoutesSomeIdRoute
  '/selective-ssr': typeof SelectiveSsrIndexRoute
  '/server-routes': typeof ServerRoutesIndexRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/server-routes/$someData/$someMoreData': typeof ServerRoutesSomeDataSomeMoreDataRoute
  '/server-routes/splat/$': typeof ServerRoutesSplatSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/client-entry-point': typeof ClientEntryPointRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/google': typeof GoogleRoute
  '/hydration-mismatches': typeof HydrationMismatchesRoute
  '/middleware': typeof MiddlewareRoute
  '/playground': typeof PlaygroundRoute
  '/posts': typeof PostsRouteWithChildren
  '/server-entry-point': typeof ServerEntryPointRoute
  '/simple-server-route': typeof SimpleServerRouteRoute
  '/api/demo-names': typeof ApiDemoNamesRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/selective-ssr/client-side-render': typeof SelectiveSsrClientSideRenderRoute
  '/selective-ssr/data-only-rendering': typeof SelectiveSsrDataOnlyRenderingRoute
  '/server-routes/$someId': typeof ServerRoutesSomeIdRoute
  '/selective-ssr/': typeof SelectiveSsrIndexRoute
  '/server-routes/': typeof ServerRoutesIndexRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/server-routes/$someData/$someMoreData': typeof ServerRoutesSomeDataSomeMoreDataRoute
  '/server-routes/splat/$': typeof ServerRoutesSplatSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/client-entry-point'
    | '/error-boundary'
    | '/google'
    | '/hydration-mismatches'
    | '/middleware'
    | '/playground'
    | '/posts'
    | '/server-entry-point'
    | '/simple-server-route'
    | '/api/demo-names'
    | '/posts/$postId'
    | '/selective-ssr/client-side-render'
    | '/selective-ssr/data-only-rendering'
    | '/server-routes/$someId'
    | '/selective-ssr'
    | '/server-routes'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/server-routes/$someData/$someMoreData'
    | '/server-routes/splat/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/client-entry-point'
    | '/error-boundary'
    | '/google'
    | '/hydration-mismatches'
    | '/middleware'
    | '/playground'
    | '/posts'
    | '/server-entry-point'
    | '/simple-server-route'
    | '/api/demo-names'
    | '/posts/$postId'
    | '/selective-ssr/client-side-render'
    | '/selective-ssr/data-only-rendering'
    | '/server-routes/$someId'
    | '/selective-ssr'
    | '/server-routes'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/server-routes/$someData/$someMoreData'
    | '/server-routes/splat/$'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/client-entry-point'
    | '/error-boundary'
    | '/google'
    | '/hydration-mismatches'
    | '/middleware'
    | '/playground'
    | '/posts'
    | '/server-entry-point'
    | '/simple-server-route'
    | '/api/demo-names'
    | '/posts/$postId'
    | '/selective-ssr/client-side-render'
    | '/selective-ssr/data-only-rendering'
    | '/server-routes/$someId'
    | '/selective-ssr/'
    | '/server-routes/'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/server-routes/$someData/$someMoreData'
    | '/server-routes/splat/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ClientEntryPointRoute: typeof ClientEntryPointRoute
  ErrorBoundaryRoute: typeof ErrorBoundaryRoute
  GoogleRoute: typeof GoogleRoute
  HydrationMismatchesRoute: typeof HydrationMismatchesRoute
  MiddlewareRoute: typeof MiddlewareRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PostsRoute: typeof PostsRouteWithChildren
  ServerEntryPointRoute: typeof ServerEntryPointRoute
  SimpleServerRouteRoute: typeof SimpleServerRouteRoute
  ApiDemoNamesRoute: typeof ApiDemoNamesRoute
  SelectiveSsrClientSideRenderRoute: typeof SelectiveSsrClientSideRenderRoute
  SelectiveSsrDataOnlyRenderingRoute: typeof SelectiveSsrDataOnlyRenderingRoute
  ServerRoutesSomeIdRoute: typeof ServerRoutesSomeIdRoute
  SelectiveSsrIndexRoute: typeof SelectiveSsrIndexRoute
  ServerRoutesIndexRoute: typeof ServerRoutesIndexRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ServerRoutesSomeDataSomeMoreDataRoute: typeof ServerRoutesSomeDataSomeMoreDataRoute
  ServerRoutesSplatSplatRoute: typeof ServerRoutesSplatSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simple-server-route': {
      id: '/simple-server-route'
      path: '/simple-server-route'
      fullPath: '/simple-server-route'
      preLoaderRoute: typeof SimpleServerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-entry-point': {
      id: '/server-entry-point'
      path: '/server-entry-point'
      fullPath: '/server-entry-point'
      preLoaderRoute: typeof ServerEntryPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/middleware': {
      id: '/middleware'
      path: '/middleware'
      fullPath: '/middleware'
      preLoaderRoute: typeof MiddlewareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hydration-mismatches': {
      id: '/hydration-mismatches'
      path: '/hydration-mismatches'
      fullPath: '/hydration-mismatches'
      preLoaderRoute: typeof HydrationMismatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google': {
      id: '/google'
      path: '/google'
      fullPath: '/google'
      preLoaderRoute: typeof GoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-boundary': {
      id: '/error-boundary'
      path: '/error-boundary'
      fullPath: '/error-boundary'
      preLoaderRoute: typeof ErrorBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-entry-point': {
      id: '/client-entry-point'
      path: '/client-entry-point'
      fullPath: '/client-entry-point'
      preLoaderRoute: typeof ClientEntryPointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-routes/': {
      id: '/server-routes/'
      path: '/server-routes'
      fullPath: '/server-routes'
      preLoaderRoute: typeof ServerRoutesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/': {
      id: '/selective-ssr/'
      path: '/selective-ssr'
      fullPath: '/selective-ssr'
      preLoaderRoute: typeof SelectiveSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-routes/$someId': {
      id: '/server-routes/$someId'
      path: '/server-routes/$someId'
      fullPath: '/server-routes/$someId'
      preLoaderRoute: typeof ServerRoutesSomeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/data-only-rendering': {
      id: '/selective-ssr/data-only-rendering'
      path: '/selective-ssr/data-only-rendering'
      fullPath: '/selective-ssr/data-only-rendering'
      preLoaderRoute: typeof SelectiveSsrDataOnlyRenderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selective-ssr/client-side-render': {
      id: '/selective-ssr/client-side-render'
      path: '/selective-ssr/client-side-render'
      fullPath: '/selective-ssr/client-side-render'
      preLoaderRoute: typeof SelectiveSsrClientSideRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/api/demo-names': {
      id: '/api/demo-names'
      path: '/api/demo-names'
      fullPath: '/api/demo-names'
      preLoaderRoute: typeof ApiDemoNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-routes/splat/$': {
      id: '/server-routes/splat/$'
      path: '/server-routes/splat/$'
      fullPath: '/server-routes/splat/$'
      preLoaderRoute: typeof ServerRoutesSplatSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server-routes/$someData/$someMoreData': {
      id: '/server-routes/$someData/$someMoreData'
      path: '/server-routes/$someData/$someMoreData'
      fullPath: '/server-routes/$someData/$someMoreData'
      preLoaderRoute: typeof ServerRoutesSomeDataSomeMoreDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ClientEntryPointRoute: ClientEntryPointRoute,
  ErrorBoundaryRoute: ErrorBoundaryRoute,
  GoogleRoute: GoogleRoute,
  HydrationMismatchesRoute: HydrationMismatchesRoute,
  MiddlewareRoute: MiddlewareRoute,
  PlaygroundRoute: PlaygroundRoute,
  PostsRoute: PostsRouteWithChildren,
  ServerEntryPointRoute: ServerEntryPointRoute,
  SimpleServerRouteRoute: SimpleServerRouteRoute,
  ApiDemoNamesRoute: ApiDemoNamesRoute,
  SelectiveSsrClientSideRenderRoute: SelectiveSsrClientSideRenderRoute,
  SelectiveSsrDataOnlyRenderingRoute: SelectiveSsrDataOnlyRenderingRoute,
  ServerRoutesSomeIdRoute: ServerRoutesSomeIdRoute,
  SelectiveSsrIndexRoute: SelectiveSsrIndexRoute,
  ServerRoutesIndexRoute: ServerRoutesIndexRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ServerRoutesSomeDataSomeMoreDataRoute: ServerRoutesSomeDataSomeMoreDataRoute,
  ServerRoutesSplatSplatRoute: ServerRoutesSplatSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
