/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DatabaseDashboardRouteImport } from './routes/database-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const DatabaseDashboardRoute = DatabaseDashboardRouteImport.update({
  id: '/database-dashboard',
  path: '/database-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database-dashboard': typeof DatabaseDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database-dashboard': typeof DatabaseDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database-dashboard': typeof DatabaseDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database-dashboard'
  id: '__root__' | '/' | '/database-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseDashboardRoute: typeof DatabaseDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/database-dashboard': {
      id: '/database-dashboard'
      path: '/database-dashboard'
      fullPath: '/database-dashboard'
      preLoaderRoute: typeof DatabaseDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseDashboardRoute: DatabaseDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
